---
openapi: 3.0.3
info:
  title: 'REFORMERS Digital Twin: Model API Server'
  description: |
    This API provides the model creation and validation capabilities of the digital twin.
    A family of models, which can be data or equation-based, is created in an automated way by the digital twin.
    The models differ in resolution and computational complexity, spanning different energy vectors (heat, electricity, gas) and having different time and component details.
    The models are calibrated to real-world data.
    These models are used by different digital twin services

    _Funding acknowledgement_:
    The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211)

  license:
    name: MIT
    url: https://opensource.org/license/mit
  version: v0.1
  x-logo:
    url: https://reformers-energyvalleys.eu/root/wp-content/themes/rerformers-theme/assets/img/logo-reformers.svg
    href: https://reformers-energyvalleys.eu

externalDocs:
  description: Find out more about REFORMERS
  url: https://reformers-energyvalleys.eu


servers:
- url: 'https://reformers-dev.vlab-central.ait.ac.at'

components:
  securitySchemes:
    $ref: './components/securitySchemes/bearer_auth.yaml'

security:
- BearerAuthentication: []

tags:
- name: Model Generators
  description: Retrieve information about model generators
- name: Models
  description: Create models and retrieve model information
- name: Status
  description: Retrieve information about model generation tasks
- name: Info
  description: Retrieve additional information about model API

paths:
  /:
    $ref: paths/index.yaml
  /model-generators:
    $ref: paths/model-generators.yaml
  /model-generators/{generator-name}/{generator-tag}:
    $ref: paths/model-generators@{name}@{tag}.yaml
  /model-generators/{generator-name}/{generator-tag}/models:
    $ref: paths/model-generators@{name}@{tag}@models.yaml
  /model-generators/{generator-name}/{generator-tag}/status:
    $ref: paths/model-generators@{name}@{tag}@status.yaml
